import { getVideoById } from "../_utils/utils";

function NewlineText({ text }: { text: string }) {
  const newText = text.split("\n").map((str, index, array) =>
    index === array.length - 1 ? (
      str
    ) : (
      <span key={index}>
        <span key={index}>{str}</span>
        <br />
      </span>
    )
  );

  return <div>{newText}</div>;
}

export default function Video({ params }: { params: { videoId: string } }) {
  const video = getVideoById(params.videoId);
  if (!video) return <div>Video not found</div>;

  return (
    <div className="w-full">
      <div className="text-stone-700 mt-8 bg-stone-50 p-8 rounded-lg shadow-lg">
        <iframe
          className="w-full aspect-video"
          src={`https://www.youtube.com/embed/${video.videoId}`}
          title={video.title}
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowFullScreen
        />

        <div className="my-8">
          <h1 className="text-3xl font-light text-stone-500 pb-3">
            {video.title}
          </h1>
          <div className="text-zinc-400 text-medium pb-3 text-sm">
            {video.channelTitle} - {video.publishedAt.toLocaleDateString()}
          </div>
        </div>

        {video.summary ? (
          <div className="text-stone-700 bg-stone-200 p-8 rounded-lg">
            <div className="text-xs font-mono text-stone-500 font-semibold mb-4">
              AI Generated Summary
            </div>
            <NewlineText text={video.summary} />

            <div className="text-xs text-center font-mono text-stone-400 font-semibold mt-8">
              This summary was generated by GPT and may contain errors.
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}
